# Generated by Django 3.2.7 on 2021-09-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishes',
            name='completed_date',
        ),
        migrations.AddField(
            model_name='wishes',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
